### ISSUE TITLE
no longer works with sd.next

### ISSUE THREAD

**Issue by Raivshard** [ljleb/sd-webui-neutral-prompt#29]
Cool extension, but you'll have to talk to vlad if you want that to change. Quite a few "invasive" extensions no longer function with it.

**Comment by ljleb** [comment]
I'll take a look and will ping him if I can't fix it because of incompatibilities with the structure of a1111. I don't want to maintain a webui host switch case.

**Comment by ljleb** [comment]
I ran some tests and it seems to work. One problem I encountered is that restarting sd.next using the button in the settings will break the extension. I believe this is because vlad's fork doesn't call the unregister callback used to remove monkey patches. This makes the extension hijack the `sd_samplers.create_sampler` function twice, which then breaks some assumptions made in the second call. I can fix this on my side, but this extension is probably not the only one affected by this behavior. It should be reported in vlad's fork instead imo.
